# Buildpack API version
api = "0.5"

# Buildpack ID and metadata
[buildpack]
id = "dev.snowdrop.buildpacks.dummy"
version = "0.0.1"
name = "Snowdrop dummy native Buildpack"

# Stacks that the buildpack will work with
[[stacks]]
id = "dev.snowdrop.buildpacks.stack.jvm"
