# Buildpacks to include in builder
[[buildpacks]]
uri = "../../buildpacks/snowdrop-maven"

[[buildpacks]]
uri = "../../buildpacks/snowdrop-expanded-jar"

[[order]]
    [[order.group]]
    id = "dev.snowdrop.buildpacks.snowdrop-maven"
    version = "0.0.1"

[[order]]
    [[order.group]]
    id = "dev.snowdrop.buildpacks.snowdrop-expanded-jar"
    version = "0.0.1"

# Stack that will be used by the builder
[stack]
id = "dev.snowdrop.buildpacks.stack.jvm"
run-image = "redhat/buildpacks-stack-snowdrop-run:jvm"
build-image = "redhat/buildpacks-stack-snowdrop-build:jvm"
