# Buildpacks to include within the Builder
[[buildpacks]]
uri = "../../buildpacks/maven"

[[buildpacks]]
uri = "../../buildpacks/dummy"

# dev.snowdrop.buildpack.build pack content could also be defined as a OCI image uri
# if the buildpack hs been created as OCI image "pack buildpack package snowdrop/maven-bp --config ./package.toml"
# uri = "docker://snowdrop/maven-bp"

[[order]]
    [[order.group]]
    id = "dev.snowdrop.buildpacks.dummy"
    version = "0.0.1"

    [[order.group]]
    id = "dev.snowdrop.buildpacks.maven"
    version = "0.0.1"

# Stack(s) that will be used by the Builder
[stack]
id = "dev.snowdrop.buildpacks.stack.jvm"
run-image = "redhat/buildpacks-stack-snowdrop-run:jvm"
build-image = "redhat/buildpacks-stack-snowdrop-build:jvm"
