# Buildpacks to include within the Builder
[[buildpacks]]
uri = "../../buildpacks/maven"

[[order]]
    [[order.group]]
    id = "dev.snowdrop.buildpacks.buildpack"
    version = "0.0.1"

# Stack(s) that will be used by the Builder
[stack]
id = "dev.snowdrop.buildpacks.stack.jvm"
run-image = "redhat/buildpacks-stack-snowdrop-run:jvm"
build-image = "redhat/buildpacks-stack-snowdrop-build:jvm"
