# Buildpack API version
api = "0.5"

# Buildpack ID and metadata
[buildpack]
id = "dev.snowdrop.buildpacks.maven"
version = "0.0.1"
name = "Snowdrop Maven Buildpack"

# Stacks that the buildpack will work with
[[stacks]]
id = "dev.snowdrop.buildpacks.stack.jvm"
